apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
kind: ControllerManagerConfig
health:
  healthProbeBindAddress: :8081
metrics:
  bindAddress: 0.0.0.0:8080
webhook:
  port: 9443
leaderElection:
  leaderElect: true
  resourceName: 73585216.nais.io
