---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: aura
  name: bqrator
  namespace: nais
spec:
  accessPolicy:
    inbound:
      rules:
      - application: prometheus
    outbound:
      external:
      - host: bigquery.googleapis.com
  image: ghcr.io/nais/bqrator:2
  liveness:
    failureThreshold: 3
    initialDelay: 15
    path: /healthz
    periodSeconds: 20
    timeout: 1
    port: 8081
  port: 8080
  prometheus:
    enabled: true
  readiness:
    initialDelay: 5
    periodSeconds: 10
    path: /readyz
    port: 8081
  replicas:
    cpuThresholdPercentage: 50
    max: 1
    min: 1
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi