apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/project-id: nais-dev-2e7b
    cnrm.cloud.google.com/state-into-spec: merge
    nais.io/team: nais
  labels:
    app: bqrator
    team: aura
  name: bqrator
  namespace: serviceaccounts
spec:
  displayName: bqrator
  resourceID: bqrator-nais-3dvamby
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: bqrator-nais-3dvamby@nais-dev-2e7b.iam.gserviceaccount.com
  labels:
    app: bqrator
    team: aura
  name: bqrator
  namespace: nais
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bqrator
  namespace: nais
  labels:
    app: bqrator
    team: aura
spec:
  selector:
    matchLabels:
      app: bqrator
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: bqrator
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app: bqrator
    spec:
      securityContext:
        runAsNonRoot: true
      imagePullSecrets:
      - name: gh-docker-credentials
      containers:
      - command:
        - /manager
        args:
        - --leader-elect
        image: ghcr.io/nais/bqrator:latest
        name: bqrator
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: bqrator
      terminationGracePeriodSeconds: 10
