apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{ include "bqrator.name" . }}
  labels:
    {{- include "bqrator.labels" . | nindent 4 }}
    team: nais-system
spec:
  accessPolicy:
    inbound:
      rules:
        - application: prometheus
    outbound:
      external:
        - host: bigquery.googleapis.com
  image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
  liveness:
    failureThreshold: 3
    initialDelay: 15
    path: /healthz
    periodSeconds: 20
    timeout: 1
    port: 8081
  port: 8080
  prometheus:
    enabled: true
  readiness:
    initialDelay: 5
    periodSeconds: 10
    path: /readyz
    port: 8081
  replicas:
    {{- toYaml .Values.replicas | nindent 4}}
  resources:
    {{- toYaml .Values.resources | nindent 4 }}
