apiVersion: networking.gke.io/v1alpha3
kind: FQDNNetworkPolicy
metadata:
  name: {{ include "bqrator.name" . }}-fqdn
  labels:
    {{- include "bqrator.labels" . | nindent 4 }}
spec:
  egress:
    - ports:
      - port: 80
        protocol: TCP
      to:
      - fqdns:
        - metadata.google.internal
    - ports:
        - port: 443
          protocol: TCP
      to:
        - fqdns:
            - bigquery.googleapis.com
  podSelector:
    matchLabels:
      {{- include "bqrator.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
