apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "bqrator.name" . }}
  labels:
    {{- include "bqrator.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "bqrator.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
  - port: http
    path: /metrics
    interval: 1m
    scrapeTimeout: 10s
