apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: "{{ .Values.gcpServiceAccount }}"
  name: {{ include "bqrator.name" . }}
  labels:
    {{- include "bqrator.labels" . | nindent 4 }}
