apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "bqrator.name" . }}
  labels:
    {{- include "bqrator.labels" . | nindent 4 }}
spec:
  egress:
    - to:
      - ipBlock:
          cidr: {{ .Values.apiCidr | quote }}
  podSelector:
    matchLabels:
      {{- include "bqrator.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
