# permissions for end users to view bigquerydatasets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bigquerydataset-viewer-role
rules:
- apiGroups:
  - nais.io.nais.io
  resources:
  - bigquerydatasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nais.io.nais.io
  resources:
  - bigquerydatasets/status
  verbs:
  - get
