# permissions for end users to edit bigquerydatasets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bigquerydataset-editor-role
rules:
- apiGroups:
  - nais.io.nais.io
  resources:
  - bigquerydatasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nais.io.nais.io
  resources:
  - bigquerydatasets/status
  verbs:
  - get
