---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bqrator
rules:
- apiGroups:
  - google.nais.io
  resources:
  - bigquerydatasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - google.nais.io
  resources:
  - bigquerydatasets/finalizers
  verbs:
  - update
- apiGroups:
  - google.nais.io
  resources:
  - bigquerydatasets/status
  verbs:
  - get
  - patch
  - update
