---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bqrator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bqrator
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system