---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/project-id: nais-dev-2e7b
    cnrm.cloud.google.com/state-into-spec: merge
    nais.io/team: nais
  labels:
    app: bqrator
    team: aura
  name: bqrator
  namespace: serviceaccounts
spec:
  displayName: bqrator
  resourceID: bqrator-nais-3dvamby
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: bqrator-nais-3dvamby@nais-dev-2e7b.iam.gserviceaccount.com
  labels:
    app: bqrator
    team: aura
  name: bqrator
  namespace: nais