environmentKinds:
  - "legacy"

values:
  gcpServiceAccount:
    displayName: GCP Service Account
    description: "The GCP service account to use for the application"
    computed:
      template: "{{ .Env.bqrator_sa }}"
