image:
  repository: europe-north1-docker.pkg.dev/nais-io/nais/images/bqrator
  tag: "main"

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

fasit: # mapped from Fasit
  tenant:
    name: ""
