apiVersion: google.nais.io/v1
kind: BigQueryDataset
metadata:
  name: bigquerydataset-sample
spec:
  name: bqrater_test_set2
  description: "Supert datasett som har data fra tidenes morgen"
  location: europe-north1
  access:
    - role: READER
      userByEmail: frode.sundby@nav.no
    - role: OWNER
      userByEmail: thomas.siegfried.krampl@nav.no
  project: nada-dev-db2e
  cascadingDelete: true
