name: Build and push image

on:
  push:
    branches:
      - main
    paths-ignore:
      - "charts/**"
      - "*.md"

env:
  IMAGE: bqrator
  GOOGLE_SA_USER: gh-bqrator

jobs:
  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # ratchet:actions/checkout@v3
      - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # ratchet:actions/setup-go@v3
        with:
          go-version: "^1.21"
      - name: Run tests
        run: make test

  build_and_push:
    needs: integration-tests
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    env:
      RUNNER_IMG: "gcr.io/distroless/static-debian11"
      RUNNERIMG_IDENTITY: "keyless@distroless.iam.gserviceaccount.com"
      RUNNERIMG_ISSUER: "https://accounts.google.com"
    steps:
      - name: Checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # ratchet:actions/checkout@v3
      - name: Install cosign
        uses: sigstore/cosign-installer@9e9de2292db7abb3f51b7f4808d98f0d347a8919 # ratchet:sigstore/cosign-installer@main
        with:
          cosign-release: 'v2.1.1'
      - name: Verify runner image
        run: cosign verify --certificate-identity ${{ env.RUNNERIMG_IDENTITY }} --certificate-oidc-issuer ${{ env.RUNNERIMG_ISSUER }} ${{ env.RUNNER_IMG }}
      - uses: nais/build-push-sign@7ec7617aae88394f31653b30c0b20b5706678396 # ratchet:nais/build-push-sign@main
        id: build-push-sign
        with:
          name: ${{ env.IMAGE }}
          google_service_account: ${{ env.GOOGLE_SA_USER }}
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
          push: ${{ github.actor != 'dependabot[bot]' }}
