name: Build and deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "*.env"
  pull_request:
    types: [opened, synchronize, labeled]

permissions:
  contents: write
  id-token: write

jobs:
  build-deploy:
    uses: nais/actions/.github/workflows/mise-build-deploy-fasit.yaml@aa4b3f170c7d73bc435f0176e99e7072814e87db # ratchet:nais/actions/.github/workflows/mise-build-deploy-fasit.yaml@main
    with:
      builds-chart: true
      deploys-to-fasit: true
      targets: |
        [
          { "target": { "kind": "tenant", "tenant": "ci-nais" }, "wait": true },
          { "target": { "kind": "tenant" } }
        ]
      deploy-pr-targets: |
        [ { "target": { "kind": "tenant", "tenant": "dev-nais" } } ]
      mise-tasks: '["test", "check"]'
    secrets:
      NAIS_IO_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
